using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Data_Base_Bank.Models
{
    public enum SortState
    {
        CurrencyIDAsc,
        CurrencyIDDesc,
        NameOfCurrencyAsc,
        NameOfCurrencyDesc,
        ExchangerateOfCurrencyAsc,
        ExchangerateOfCurrencyDesc,
        DateOfCurrencyAsc,
        DateOfCurrencyDesc,
        DepositorIDAsc,
        DepositorIDDesc,
        NameOfDepAsc,
        NameOfDepDesc,
        SurnameOfDepAsc,
        SurnameOfDepDesc,
        MiddlenameOfDepAsc,
        MiddlenameOfDepDesc,
        AddresAsc,
        AddresDesc,
        PhoneAsc,
        PhoneDesc,
        PassportdataAsc,
        PassportdataDesc,
        EmployeeIDAsc,
        EmployeeIDDesc,
        NameOfEmplAsc,
        NameOfEmplDesc,
        SurnameOfEmplAsc,
        SurnameOfEmplDesc,
        MiddlenameOfEmplAsc,
        MiddlenameOfEmplDesc,
        PatronymicAsc,
        PatronymicDesc,
        DateofBirthAsc,
        DateofBirthDesc,
        TypedepositIDAsc,
        TypedepositIDDesc,
        NameOfTypeAsc,
        NameOfTypeDesc,
        MinimumTermOfdepositAsc,
        MinimumTermOfdepositDesc,
        MinimumDepositAmountAsc,
        MinimumDepositAmountDesc,
        InterestrateAsc,
        InterestrateDesc,
        AdditionalconditionsAsc,
        AdditionalconditionsDesc,
        DespositIDAsc,
        DespositIDDesc,
        TypeOfCurrencyAsc,
        TypeOfCurrencyDesc,
        TypeOfDepositorAsc,
        TypeOfDepositorDesc,
        TypeOfTypedepositAsc,
        TypeOfTypedepositDesc,
        TypeOfEmployeeAsc,
        TypeOfEmployeeDesc,
        DepositsumAsc,
        DepositsumDesc,
        DatedepositAsc,
        DatedepositDesc,
        RefundamountAsc,
        RefundamountDesc,
        DatereturnAsc,
        DatereturnDesc
    };
}
